const stocks = [
    { ticker: 'AAPL', name: 'Apple Inc.' },
    { ticker: 'NVDA', name: 'NVIDIA Corporation' },
    { ticker: 'MSFT', name: 'Microsoft Corporation' },
    { ticker: 'GOOG', name: 'Alphabet Inc.' },
    { ticker: 'GOOGL', name: 'Alphabet Inc.' },
    { ticker: 'AMZN', name: 'Amazon.com, Inc.' },
    { ticker: 'META', name: 'Meta Platforms, Inc.' },
    { ticker: 'BRK.B', name: 'Berkshire Hathaway Inc.' },
    { ticker: 'LLY', name: 'Eli Lilly and Company' },
    { ticker: 'AVGO', name: 'Broadcom Inc.' },
    { ticker: 'TSLA', name: 'Tesla, Inc.' },
    { ticker: 'WMT', name: 'Walmart Inc.' },
    { ticker: 'JPM', name: 'JPMorgan Chase & Co.' },
    { ticker: 'XOM', name: 'Exxon Mobil Corporation' },
    { ticker: 'V', name: 'Visa Inc.' },
    { ticker: 'UNH', name: 'UnitedHealth Group Incorporated' },
    { ticker: 'ORCL', name: 'Oracle Corporation' },
    { ticker: 'MA', name: 'Mastercard Incorporated' },
    { ticker: 'HD', name: 'The Home Depot, Inc.' },
    { ticker: 'PG', name: 'The Procter & Gamble Company' },
    { ticker: 'COST', name: 'Costco Wholesale Corporation' },
    { ticker: 'JNJ', name: 'Johnson & Johnson' },
    { ticker: 'ABBV', name: 'AbbVie Inc.' },
    { ticker: 'BAC', name: 'Bank of America Corporation' },
    { ticker: 'KO', name: 'The Coca-Cola Company' },
    { ticker: 'NFLX', name: 'Netflix, Inc.' },
    { ticker: 'MRK', name: 'Merck & Co., Inc.' },
    { ticker: 'CRM', name: 'Salesforce, Inc.' },
    { ticker: 'CVX', name: 'Chevron Corporation' },
    { ticker: 'AMD', name: 'Advanced Micro Devices, Inc.' },
    { ticker: 'TMUS', name: 'T-Mobile US, Inc.' },
    { ticker: 'PEP', name: 'PepsiCo, Inc.' },
    { ticker: 'ACN', name: 'Accenture plc' },
    { ticker: 'LIN', name: 'Linde plc' },
    { ticker: 'TMO', name: 'Thermo Fisher Scientific Inc.' },
    { ticker: 'MCD', name: 'McDonalds Corporation' },
    { ticker: 'ADBE', name: 'Adobe Inc.' },
    { ticker: 'CSCO', name: 'Cisco Systems, Inc.' },
    { ticker: 'IBM', name: 'International Business Machines Corporation' },
    { ticker: 'WFC', name: 'Wells Fargo & Company' },
    { ticker: 'GE', name: 'General Electric Company' },
    { ticker: 'ABT', name: 'Abbott Laboratories' },
    { ticker: 'AXP', name: 'American Express Company' },
    { ticker: 'DHR', name: 'Danaher Corporation' },
    { ticker: 'QCOM', name: 'QUALCOMM Incorporated' },
    { ticker: 'NOW', name: 'ServiceNow, Inc.' },
    { ticker: 'CAT', name: 'Caterpillar Inc.' },
    { ticker: 'PM', name: 'Philip Morris International Inc.' },
    { ticker: 'VZ', name: 'Verizon Communications Inc.' },
    { ticker: 'TXN', name: 'Texas Instruments Incorporated' },
    { ticker: 'UBER', name: 'Uber Technologies, Inc.' },
    { ticker: 'AMGN', name: 'Amgen Inc.' },
    { ticker: 'INTU', name: 'Intuit Inc.' },
    { ticker: 'GS', name: 'The Goldman Sachs Group, Inc.' },
    { ticker: 'DIS', name: 'The Walt Disney Company' },
    { ticker: 'NEE', name: 'NextEra Energy, Inc.' },
    { ticker: 'ISRG', name: 'Intuitive Surgical, Inc.' },
    { ticker: 'PFE', name: 'Pfizer Inc.' },
    { ticker: 'RTX', name: 'RTX Corporation' },
    { ticker: 'SPGI', name: 'S&P Global Inc.' },
    { ticker: 'CMCSA', name: 'Comcast Corporation' },
    { ticker: 'LOW', name: 'Lowes Companies, Inc.' },
    { ticker: 'AMAT', name: 'Applied Materials, Inc.' },
    { ticker: 'T', name: 'AT&T Inc.' },
    { ticker: 'UNP', name: 'Union Pacific Corporation' },
    { ticker: 'BLK', name: 'BlackRock, Inc.' },
    { ticker: 'PGR', name: 'The Progressive Corporation' },
    { ticker: 'BKNG', name: 'Booking Holdings Inc.' },
    { ticker: 'LMT', name: 'Lockheed Martin Corporation' },
    { ticker: 'HON', name: 'Honeywell International Inc.' },
    { ticker: 'SYK', name: 'Stryker Corporation' },
    { ticker: 'ETN', name: 'Eaton Corporation plc' },
    { ticker: 'TJX', name: 'The TJX Companies, Inc.' },
    { ticker: 'SCHW', name: 'The Charles Schwab Corporation' },
    { ticker: 'BSX', name: 'Boston Scientific Corporation' },
    { ticker: 'VRTX', name: 'Vertex Pharmaceuticals Incorporated' },
    { ticker: 'ANET', name: 'Arista Networks, Inc.' },
    { ticker: 'NKE', name: 'NIKE, Inc.' },
    { ticker: 'PANW', name: 'Palo Alto Networks, Inc.' },
    { ticker: 'KKR', name: 'KKR & Co. Inc.' },
    { ticker: 'BX', name: 'Blackstone Inc.' },
    { ticker: 'C', name: 'Citigroup Inc.' },
    { ticker: 'ADP', name: 'Automatic Data Processing, Inc.' },
    { ticker: 'MU', name: 'Micron Technology, Inc.' },
    { ticker: 'MDT', name: 'Medtronic plc' },
    { ticker: 'UPS', name: 'United Parcel Service, Inc.' },
    { ticker: 'PLD', name: 'Prologis, Inc.' },
    { ticker: 'ELV', name: 'Elevance Health, Inc.' },
    { ticker: 'ADI', name: 'Analog Devices, Inc.' },
    { ticker: 'FIS', name: 'Fidelity National Information Services, Inc.' },
    { ticker: 'MMC', name: 'Marsh & McLennan Companies, Inc.' },
    { ticker: 'CB', name: 'Chubb Limited' },
    { ticker: 'DE', name: 'Deere & Company' },
    { ticker: 'REGN', name: 'Regeneron Pharmaceuticals, Inc.' },
    { ticker: 'SBUX', name: 'Starbucks Corporation' },
    { ticker: 'AMT', name: 'American Tower Corporation' },
    { ticker: 'BMY', name: 'Bristol-Myers Squibb Company' },
    { ticker: 'GILD', name: 'Gilead Sciences, Inc.' },
    { ticker: 'HCA', name: 'HCA Healthcare, Inc.' },
    { ticker: 'SO', name: 'The Southern Company' },
    { ticker: 'LRCX', name: 'Lam Research Corporation' },
    { ticker: 'SHW', name: 'The Sherwin-Williams Company' },
    { ticker: 'CI', name: 'The Cigna Group' },
    { ticker: 'INTC', name: 'Intel Corporation' },
    { ticker: 'MDLZ', name: 'Mondelez International, Inc.' },
    { ticker: 'PLTR', name: 'Palantir Technologies Inc.' },
    { ticker: 'ICE', name: 'Intercontinental Exchange, Inc.' },
    { ticker: 'KLAC', name: 'KLA Corporation' },
    { ticker: 'BA', name: 'The Boeing Company' },
    { ticker: 'DUK', name: 'Duke Energy Corporation' },
    { ticker: 'TT', name: 'Trane Technologies plc' },
    { ticker: 'MCO', name: 'Moodys Corporation' },
    { ticker: 'DELL', name: 'Dell Technologies Inc.' },
    { ticker: 'ZTS', name: 'Zoetis Inc.' },
    { ticker: 'WM', name: 'Waste Management, Inc.' },
    { ticker: 'MO', name: 'Altria Group, Inc.' },
    { ticker: 'CTAS', name: 'Cintas Corporation' },
    { ticker: 'ABNB', name: 'Airbnb, Inc.' },
    { ticker: 'CEG', name: 'Constellation Energy Corporation' },
    { ticker: 'CL', name: 'Colgate-Palmolive Company' },
    { ticker: 'GD', name: 'General Dynamics Corporation' },
    { ticker: 'PH', name: 'Parker-Hannifin Corporation' },
    { ticker: 'CMG', name: 'Chipotle Mexican Grill, Inc.' },
    { ticker: 'CVS', name: 'CVS Health Corporation' },
    { ticker: 'PYPL', name: 'PayPal Holdings, Inc.' },
    { ticker: 'CME', name: 'CME Group Inc.' },
    { ticker: 'WELL', name: 'Welltower Inc.' },
    { ticker: 'SNPS', name: 'Synopsys, Inc.' },
    { ticker: 'APH', name: 'Amphenol Corporation' },
    { ticker: 'MSI', name: 'Motorola Solutions, Inc.' },
    { ticker: 'TDG', name: 'TransDigm Group Incorporated' },
    { ticker: 'AON', name: 'Aon plc' },
    { ticker: 'ITW', name: 'Illinois Tool Works Inc.' },
    { ticker: 'NOC', name: 'Northrop Grumman Corporation' },
    { ticker: 'PNC', name: 'The PNC Financial Services Group, Inc.' },
    { ticker: 'MMM', name: '3M Company' },
    { ticker: 'CRWD', name: 'CrowdStrike Holdings, Inc.' },
    { ticker: 'TGT', name: 'Target Corporation' },
    { ticker: 'CDNS', name: 'Cadence Design Systems, Inc.' },
    { ticker: 'CARR', name: 'Carrier Global Corporation' },
    { ticker: 'ECL', name: 'Ecolab Inc.' },
    { ticker: 'MAR', name: 'Marriott International, Inc.' },
    { ticker: 'USB', name: 'U.S. Bancorp' },
    { ticker: 'GEV', name: 'GE Vernova Inc.' },
    { ticker: 'EOG', name: 'EOG Resources, Inc.' },
    { ticker: 'APD', name: 'Air Products and Chemicals, Inc.' },
    { ticker: 'BDX', name: 'Becton, Dickinson and Company' },
    { ticker: 'ORLY', name: 'OReilly Automotive, Inc.' },
    { ticker: 'CSX', name: 'CSX Corporation' },
    { ticker: 'FCX', name: 'Freeport-McMoRan Inc.' },
    { ticker: 'MCK', name: 'McKesson Corporation' },
    { ticker: 'FDX', name: 'FedEx Corporation' },
    { ticker: 'RSG', name: 'Republic Services, Inc.' },
    { ticker: 'AFL', name: 'Aflac Incorporated' },
    { ticker: 'NEM', name: 'Newmont Corporation' },
    { ticker: 'FTNT', name: 'Fortinet, Inc.' },
    { ticker: 'AJG', name: 'Arthur J. Gallagher & Co.' },
    { ticker: 'EMR', name: 'Emerson Electric Co.' },
    { ticker: 'WMB', name: 'The Williams Companies, Inc.' },
    { ticker: 'DHI', name: 'D.R. Horton, Inc.' },
    { ticker: 'ADSK', name: 'Autodesk, Inc.' },
    { ticker: 'SLB', name: 'Schlumberger Limited' },
    { ticker: 'PSA', name: 'Public Storage' },
    { ticker: 'MET', name: 'MetLife, Inc.' },
    { ticker: 'COF', name: 'Capital One Financial Corporation' },
    { ticker: 'ROP', name: 'Roper Technologies, Inc.' },
    { ticker: 'NXPI', name: 'NXP Semiconductors N.V.' },
    { ticker: 'TFC', name: 'Truist Financial Corporation' },
    { ticker: 'HLT', name: 'Hilton Worldwide Holdings Inc.' },
    { ticker: 'NSC', name: 'Norfolk Southern Corporation' },
    { ticker: 'SPG', name: 'Simon Property Group, Inc.' },
    { ticker: 'PCAR', name: 'PACCAR Inc' },
    { ticker: 'OKE', name: 'ONEOK, Inc.' },
    { ticker: 'BK', name: 'The Bank of New York Mellon Corporation' },
    { ticker: 'O', name: 'Realty Income Corporation' },
    { ticker: 'URI', name: 'United Rentals, Inc.' },
    { ticker: 'PSX', name: 'Phillips 66' },
    { ticker: 'KMI', name: 'Kinder Morgan, Inc.' },
    { ticker: 'TRV', name: 'The Travelers Companies, Inc.' },
    { ticker: 'RCL', name: 'Royal Caribbean Cruises Ltd.' },
    { ticker: 'GM', name: 'General Motors Company' },
    { ticker: 'SRE', name: 'Sempra' },
    { ticker: 'AEP', name: 'American Electric Power Company, Inc.' },
    { ticker: 'GWW', name: 'W.W. Grainger, Inc.' },
    { ticker: 'FANG', name: 'Diamondback Energy, Inc.' },
    { ticker: 'CPRT', name: 'Copart, Inc.' },
    { ticker: 'DLR', name: 'Digital Realty Trust, Inc.' },
    { ticker: 'MPC', name: 'Marathon Petroleum Corporation' },
    { ticker: 'AZO', name: 'AutoZone, Inc.' },
    { ticker: 'MNST', name: 'Monster Beverage Corporation' },
    { ticker: 'PAYX', name: 'Paychex, Inc.' },
    { ticker: 'JCI', name: 'Johnson Controls International plc' },
    { ticker: 'ALL', name: 'The Allstate Corporation' },
    { ticker: 'FICO', name: 'Fair Isaac Corporation' },
    { ticker: 'AMP', name: 'Ameriprise Financial, Inc.' },
    { ticker: 'LEN', name: 'Lennar Corporation' },
    { ticker: 'KDP', name: 'Keurig Dr Pepper Inc.' },
    { ticker: 'CCI', name: 'Crown Castle Inc.' },
    { ticker: 'AIG', name: 'American International Group, Inc.' },
    { ticker: 'KMB', name: 'Kimberly-Clark Corporation' },
    { ticker: 'FIS', name: 'Fidelity National Information Services, Inc.' },
    { ticker: 'ROST', name: 'Ross Stores, Inc.' },
    { ticker: 'D', name: 'Dominion Energy, Inc.' },
    { ticker: 'MSCI', name: 'MSCI Inc.' },
    { ticker: 'OXY', name: 'Occidental Petroleum Corporation' },
    { ticker: 'CHTR', name: 'Charter Communications, Inc.' },
    { ticker: 'LHX', name: 'L3Harris Technologies, Inc.' },
    { ticker: 'COR', name: 'Cencora, Inc.' },
    { ticker: 'CMI', name: 'Cummins Inc.' },
    { ticker: 'PWR', name: 'Quanta Services, Inc.' },
    { ticker: 'PRU', name: 'Prudential Financial, Inc.' },
    { ticker: 'TEL', name: 'TE Connectivity plc' },
    { ticker: 'STZ', name: 'Constellation Brands, Inc.' },
    { ticker: 'VST', name: 'Vistra Corp.' },
    { ticker: 'FAST', name: 'Fastenal Company' },
    { ticker: 'PEG', name: 'Public Service Enterprise Group Incorporated' },
    { ticker: 'PCG', name: 'PG&E Corporation' },
    { ticker: 'MPWR', name: 'Monolithic Power Systems, Inc.' },
    { ticker: 'KHC', name: 'The Kraft Heinz Company' },
    { ticker: 'ODFL', name: 'Old Dominion Freight Line, Inc.' },
    { ticker: 'VLO', name: 'Valero Energy Corporation' },
    { ticker: 'F', name: 'Ford Motor Company' },
    { ticker: 'IQV', name: 'IQVIA Holdings Inc.' },
    { ticker: 'HWM', name: 'Howmet Aerospace Inc.' },
    { ticker: 'NDAQ', name: 'Nasdaq, Inc.' },
    { ticker: 'OTIS', name: 'Otis Worldwide Corporation' },
    { ticker: 'HES', name: 'Hess Corporation' },
    { ticker: 'KVUE', name: 'Kenvue Inc.' },
    { ticker: 'A', name: 'Agilent Technologies, Inc.' },
    { ticker: 'EW', name: 'Edwards Lifesciences Corporation' },
    { ticker: 'GEHC', name: 'GE HealthCare Technologies Inc.' },
    { ticker: 'IT', name: 'Gartner, Inc.' },
    { ticker: 'IR', name: 'Ingersoll Rand Inc.' },
    { ticker: 'KR', name: 'The Kroger Co.' },
    { ticker: 'EXC', name: 'Exelon Corporation' },
    { ticker: 'ACGL', name: 'Arch Capital Group Ltd.' },
    { ticker: 'MCHP', name: 'Microchip Technology Incorporated' },
    { ticker: 'CTVA', name: 'Corteva, Inc.' },
    { ticker: 'GIS', name: 'General Mills, Inc.' },
    { ticker: 'AME', name: 'AMETEK, Inc.' },
    { ticker: 'GLW', name: 'Corning Incorporated' },
    { ticker: 'IDXX', name: 'IDEXX Laboratories, Inc.' },
    { ticker: 'EA', name: 'Electronic Arts Inc.' },
    { ticker: 'VRSK', name: 'Verisk Analytics, Inc.' },
    { ticker: 'CTSH', name: 'Cognizant Technology Solutions Corporation' },
    { ticker: 'LVS', name: 'Las Vegas Sands Corp.' },
    { ticker: 'YUM', name: 'Yum! Brands, Inc.' },
    { ticker: 'HSY', name: 'The Hershey Company' },
    { ticker: 'SYY', name: 'Sysco Corporation' },
    { ticker: 'CBRE', name: 'CBRE Group, Inc.' },
    { ticker: 'DFS', name: 'Discover Financial Services' },
    { ticker: 'DOW', name: 'Dow Inc.' },
    { ticker: 'ED', name: 'Consolidated Edison, Inc.' },
    { ticker: 'EXR', name: 'Extra Space Storage Inc.' },
    { ticker: 'BKR', name: 'Baker Hughes Company' },
    { ticker: 'CNC', name: 'Centene Corporation' },
    { ticker: 'NUE', name: 'Nucor Corporation' },
    { ticker: 'EFX', name: 'Equifax Inc.' },
    { ticker: 'IRM', name: 'Iron Mountain Incorporated' },
    { ticker: 'HPQ', name: 'HP Inc.' },
    { ticker: 'TRGP', name: 'Targa Resources Corp.' },
    { ticker: 'DD', name: 'DuPont de Nemours, Inc.' },
    { ticker: 'XEL', name: 'Xcel Energy Inc.' },
    { ticker: 'LULU', name: 'Lululemon Athletica Inc.' },
    { ticker: 'RMD', name: 'ResMed Inc.' },
    { ticker: 'HIG', name: 'The Hartford Financial Services Group, Inc.' },
    { ticker: 'VICI', name: 'VICI Properties Inc.' },
    { ticker: 'MLM', name: 'Martin Marietta Materials, Inc.' },
    { ticker: 'DAL', name: 'Delta Air Lines, Inc.' },
    { ticker: 'VMC', name: 'Vulcan Materials Company' },
    { ticker: 'XYL', name: 'Xylem Inc.' },
    { ticker: 'EIX', name: 'Edison International' },
    { ticker: 'AXON', name: 'Axon Enterprise, Inc.' },
    { ticker: 'WAB', name: 'Westinghouse Air Brake Technologies Corporation' },
    { ticker: 'EL', name: 'The Estée Lauder Companies Inc.' },
    { ticker: 'EBAY', name: 'eBay Inc.' },
    { ticker: 'AVB', name: 'AvalonBay Communities, Inc.' },
    { ticker: 'TSCO', name: 'Tractor Supply Company' },
    { ticker: 'GRMN', name: 'Garmin Ltd.' },
    { ticker: 'CSGP', name: 'CoStar Group, Inc.' },
    { ticker: 'MTB', name: 'M&T Bank Corporation' },
    { ticker: 'HUM', name: 'Humana Inc.' },
    { ticker: 'ROK', name: 'Rockwell Automation, Inc.' },
    { ticker: 'MTD', name: 'Mettler-Toledo International Inc.' },
    { ticker: 'WEC', name: 'WEC Energy Group, Inc.' },
    { ticker: 'PPG', name: 'PPG Industries, Inc.' },
    { ticker: 'BRO', name: 'Brown & Brown, Inc.' },
    { ticker: 'FITB', name: 'Fifth Third Bancorp' },
    { ticker: 'NVR', name: 'NVR, Inc.' },
    { ticker: 'PHM', name: 'PulteGroup, Inc.' },
    { ticker: 'LYB', name: 'LyondellBasell Industries N.V.' },
    { ticker: 'ON', name: 'ON Semiconductor Corporation' },
    { ticker: 'WTW', name: 'Willis Towers Watson Public Limited Company' },
    { ticker: 'CDW', name: 'CDW Corporation' },
    { ticker: 'ANSS', name: 'ANSYS, Inc.' },
    { ticker: 'ETR', name: 'Entergy Corporation' },
    { ticker: 'EQR', name: 'Equity Residential' },
    { ticker: 'CCL', name: 'Carnival Corporation & plc' },
    { ticker: 'SMCI', name: 'Super Micro Computer, Inc.' },
    { ticker: 'BIIB', name: 'Biogen Inc.' },
    { ticker: 'K', name: 'Kellanova' },
    { ticker: 'VLTO', name: 'Veralto Corporation' },
    { ticker: 'ADM', name: 'Archer-Daniels-Midland Company' },
    { ticker: 'AWK', name: 'American Water Works Company, Inc.' },
    { ticker: 'ERIE', name: 'Erie Indemnity Company' },
    { ticker: 'KEYS', name: 'Keysight Technologies, Inc.' },
    { ticker: 'RJF', name: 'Raymond James Financial, Inc.' },
    { ticker: 'STT', name: 'State Street Corporation' },
    { ticker: 'TTWO', name: 'Take-Two Interactive Software, Inc.' },
    { ticker: 'DVN', name: 'Devon Energy Corporation' },
    { ticker: 'IFF', name: 'International Flavors & Fragrances Inc.' },
    { ticker: 'CAH', name: 'Cardinal Health, Inc.' },
    { ticker: 'FTV', name: 'Fortive Corporation' },
    { ticker: 'HPE', name: 'Hewlett Packard Enterprise Company' },
    { ticker: 'DXCM', name: 'DexCom, Inc.' },
    { ticker: 'SBAC', name: 'SBA Communications Corporation' },
    { ticker: 'VTR', name: 'Ventas, Inc.' },
    { ticker: 'LYV', name: 'Live Nation Entertainment, Inc.' },
    { ticker: 'DTE', name: 'DTE Energy Company' },
    { ticker: 'DOV', name: 'Dover Corporation' },
    { ticker: 'GPN', name: 'Global Payments Inc.' },
    { ticker: 'BR', name: 'Broadridge Financial Solutions, Inc.' },
    { ticker: 'HAL', name: 'Halliburton Company' },
    { ticker: 'NTAP', name: 'NetApp, Inc.' },
    { ticker: 'TYL', name: 'Tyler Technologies, Inc.' },
    { ticker: 'CHD', name: 'Church & Dwight Co., Inc.' },
    { ticker: 'FE', name: 'FirstEnergy Corp.' },
    { ticker: 'DECK', name: 'Deckers Outdoor Corporation' },
    { ticker: 'TROW', name: 'T. Rowe Price Group, Inc.' },
    { ticker: 'HUBB', name: 'Hubbell Incorporated' },
    { ticker: 'ROL', name: 'Rollins, Inc.' },
    { ticker: 'WY', name: 'Weyerhaeuser Company' },
    { ticker: 'PPL', name: 'PPL Corporation' },
    { ticker: 'CPAY', name: 'Corpay, Inc.' },
    { ticker: 'STX', name: 'Seagate Technology Holdings plc' },
    { ticker: 'AEE', name: 'Ameren Corporation' },
    { ticker: 'ES', name: 'Eversource Energy' },
    { ticker: 'SW', name: 'Smurfit Westrock Plc' },
    { ticker: 'BF.B', name: 'Brown-Forman Corporation' },
    { ticker: 'WDC', name: 'Western Digital Corporation' },
    { ticker: 'GDDY', name: 'GoDaddy Inc.' },
    { ticker: 'BLDR', name: 'Builders FirstSource, Inc.' },
    { ticker: 'HBAN', name: 'Huntington Bancshares Incorporated' },
    { ticker: 'LDOS', name: 'Leidos Holdings, Inc.' },
    { ticker: 'WRB', name: 'W. R. Berkley Corporation' },
    { ticker: 'STE', name: 'STERIS plc' },
    { ticker: 'PTC', name: 'PTC Inc.' },
    { ticker: 'ATO', name: 'Atmos Energy Corporation' },
    { ticker: 'MRNA', name: 'Moderna, Inc.' },
    { ticker: 'CBOE', name: 'Cboe Global Markets, Inc.' },
    { ticker: 'MKC', name: 'McCormick & Company, Incorporated' },
    { ticker: 'RF', name: 'Regions Financial Corporation' },
    { ticker: 'FSLR', name: 'First Solar, Inc.' },
    { ticker: 'COO', name: 'The Cooper Companies, Inc.' },
    { ticker: 'EQT', name: 'EQT Corporation' },
    { ticker: 'CINF', name: 'Cincinnati Financial Corporation' },
    { ticker: 'WAT', name: 'Waters Corporation' },
    { ticker: 'TSN', name: 'Tyson Foods, Inc.' },
    { ticker: 'ZBH', name: 'Zimmer Biomet Holdings, Inc.' },
    { ticker: 'ARE', name: 'Alexandria Real Estate Equities, Inc.' },
    { ticker: 'WST', name: 'West Pharmaceutical Services, Inc.' },
    { ticker: 'TDY', name: 'Teledyne Technologies Incorporated' },
    { ticker: 'UAL', name: 'United Airlines Holdings, Inc.' },
    { ticker: 'SYF', name: 'Synchrony Financial' },
    { ticker: 'CMS', name: 'CMS Energy Corporation' },
    { ticker: 'BBY', name: 'Best Buy Co., Inc.' },
    { ticker: 'PFG', name: 'Principal Financial Group, Inc.' },
    { ticker: 'TER', name: 'Teradyne, Inc.' },
    { ticker: 'INVH', name: 'Invitation Homes Inc.' },
    { ticker: 'OMC', name: 'Omnicom Group Inc.' },
    { ticker: 'CLX', name: 'The Clorox Company' },
    { ticker: 'BALL', name: 'Ball Corporation' },
    { ticker: 'STLD', name: 'Steel Dynamics, Inc.' },
    { ticker: 'PKG', name: 'Packaging Corporation of America' },
    { ticker: 'EXPE', name: 'Expedia Group, Inc.' },
    { ticker: 'GPC', name: 'Genuine Parts Company' },
    { ticker: 'CNP', name: 'CenterPoint Energy, Inc.' },
    { ticker: 'ZBRA', name: 'Zebra Technologies Corporation' },
    { ticker: 'CFG', name: 'Citizens Financial Group, Inc.' },
    { ticker: 'FOXA', name: 'Fox Corporation' },
    { ticker: 'NTRS', name: 'Northern Trust Corporation' },
    { ticker: 'HOLX', name: 'Hologic, Inc.' },
    { ticker: 'MOH', name: 'Molina Healthcare, Inc.' },
    { ticker: 'DRI', name: 'Darden Restaurants, Inc.' },
    { ticker: 'ESS', name: 'Essex Property Trust, Inc.' },
    { ticker: 'BAX', name: 'Baxter International Inc.' },
    { ticker: 'WBD', name: 'Warner Bros. Discovery, Inc.' },
    { ticker: 'APTV', name: 'Aptiv PLC' },
    { ticker: 'MAS', name: 'Masco Corporation' },
    { ticker: 'NRG', name: 'NRG Energy, Inc.' },
    { ticker: 'FOX', name: 'Fox Corporation' },
    { ticker: 'VRSN', name: 'VeriSign, Inc.' },
    { ticker: 'LUV', name: 'Southwest Airlines Co.' },
    { ticker: 'LH', name: 'Labcorp Holdings Inc.' },
    { ticker: 'FDS', name: 'FactSet Research Systems Inc.' },
    { ticker: 'MAA', name: 'Mid-America Apartment Communities, Inc.' },
    { ticker: 'JBHT', name: 'J.B. Hunt Transport Services, Inc.' },
    { ticker: 'CTRA', name: 'Coterra Energy Inc.' },
    { ticker: 'DG', name: 'Dollar General Corporation' },
    { ticker: 'AVY', name: 'Avery Dennison Corporation' },
    { ticker: 'L', name: 'Loews Corporation' },
    { ticker: 'ULTA', name: 'Ulta Beauty, Inc.' },
    { ticker: 'GEN', name: 'Gen Digital Inc.' },
    { ticker: 'J', name: 'Jacobs Solutions Inc.' },
    { ticker: 'EXPD', name: 'Expeditors International of Washington, Inc.' },
    { ticker: 'HRL', name: 'Hormel Foods Corporation' },
    { ticker: 'EG', name: 'Everest Group, Ltd.' },
    { ticker: 'DGX', name: 'Quest Diagnostics Incorporated' },
    { ticker: 'IP', name: 'International Paper Company' },
    { ticker: 'SWK', name: 'Stanley Black & Decker, Inc.' },
    { ticker: 'TXT', name: 'Textron Inc.' },
    { ticker: 'AMCR', name: 'Amcor plc' },
    { ticker: 'ALGN', name: 'Align Technology, Inc.' },
    { ticker: 'PNR', name: 'Pentair plc' },
    { ticker: 'KEY', name: 'KeyCorp' },
    { ticker: 'KIM', name: 'Kimco Realty Corporation' },
    { ticker: 'PODD', name: 'Insulet Corporation' },
    { ticker: 'IEX', name: 'IDEX Corporation' },
    { ticker: 'SWKS', name: 'Skyworks Solutions, Inc.' },
    { ticker: 'LNT', name: 'Alliant Energy Corporation' },
    { ticker: 'AKAM', name: 'Akamai Technologies, Inc.' },
    { ticker: 'DOC', name: 'Healthpeak Properties, Inc.' },
    { ticker: 'SNA', name: 'Snap-on Incorporated' },
    { ticker: 'NI', name: 'NiSource Inc.' },
    { ticker: 'CF', name: 'CF Industries Holdings, Inc.' },
    { ticker: 'NWS', name: 'News Corporation' },
    { ticker: 'RVTY', name: 'Revvity, Inc.' },
    { ticker: 'TRMB', name: 'Trimble Inc.' },
    { ticker: 'NWSA', name: 'News Corporation' },
    { ticker: 'UHS', name: 'Universal Health Services, Inc.' },
    { ticker: 'MRO', name: 'Marathon Oil Corporation' },
    { ticker: 'DPZ', name: 'Dominos Pizza, Inc.' },
    { ticker: 'NDSN', name: 'Nordson Corporation' },
    { ticker: 'UDR', name: 'UDR, Inc.' },
    { ticker: 'CE', name: 'Celanese Corporation' },
    { ticker: 'DLTR', name: 'Dollar Tree, Inc.' },
    { ticker: 'CPB', name: 'Campbell Soup Company' },
    { ticker: 'VTRS', name: 'Viatris Inc.' },
    { ticker: 'CAG', name: 'Conagra Brands, Inc.' },
    { ticker: 'JBL', name: 'Jabil Inc.' },
    { ticker: 'POOL', name: 'Pool Corporation' },
    { ticker: 'EVRG', name: 'Evergy, Inc.' },
    { ticker: 'DVA', name: 'DaVita Inc.' },
    { ticker: 'BXP', name: 'BXP, Inc.' },
    { ticker: 'JKHY', name: 'Jack Henry & Associates, Inc.' },
    { ticker: 'BG', name: 'Bunge Global SA' },
    { ticker: 'ALLE', name: 'Allegion plc' },
    { ticker: 'REG', name: 'Regency Centers Corporation' },
    { ticker: 'EMN', name: 'Eastman Chemical Company' },
    { ticker: 'JNPR', name: 'Juniper Networks, Inc.' },
    { ticker: 'SJM', name: 'The J. M. Smucker Company' },
    { ticker: 'CHRW', name: 'C.H. Robinson Worldwide, Inc.' },
    { ticker: 'INCY', name: 'Incyte Corporation' },
    { ticker: 'CPT', name: 'Camden Property Trust' },
    { ticker: 'FFIV', name: 'F5, Inc.' },
    { ticker: 'HST', name: 'Host Hotels & Resorts, Inc.' },
    { ticker: 'RL', name: 'Ralph Lauren Corporation' },
    { ticker: 'ENPH', name: 'Enphase Energy, Inc.' },
    { ticker: 'AES', name: 'The AES Corporation' },
    { ticker: 'SOLV', name: 'Solventum Corporation' },
    { ticker: 'MGM', name: 'MGM Resorts International' },
    { ticker: 'IPG', name: 'The Interpublic Group of Companies, Inc.' },
    { ticker: 'AOS', name: 'A. O. Smith Corporation' },
    { ticker: 'TECH', name: 'Bio-Techne Corporation' },
    { ticker: 'KMX', name: 'CarMax, Inc.' },
    { ticker: 'EPAM', name: 'EPAM Systems, Inc.' },
    { ticker: 'TAP', name: 'Molson Coors Beverage Company' },
    { ticker: 'ALB', name: 'Albemarle Corporation' },
    { ticker: 'TFX', name: 'Teleflex Incorporated' },
    { ticker: 'CTLT', name: 'Catalent, Inc.' },
    { ticker: 'WYNN', name: 'Wynn Resorts, Limited' },
    { ticker: 'MKTX', name: 'MarketAxess Holdings Inc.' },
    { ticker: 'NCLH', name: 'Norwegian Cruise Line Holdings Ltd.' },
    { ticker: 'BEN', name: 'Franklin Resources, Inc.' },
    { ticker: 'TPR', name: 'Tapestry, Inc.' },
    { ticker: 'LKQ', name: 'LKQ Corporation' },
    { ticker: 'GNRC', name: 'Generac Holdings Inc.' },
    { ticker: 'HII', name: 'Huntington Ingalls Industries, Inc.' },
    { ticker: 'LW', name: 'Lamb Weston Holdings, Inc.' },
    { ticker: 'DAY', name: 'Dayforce Inc.' },
    { ticker: 'MHK', name: 'Mohawk Industries, Inc.' },
    { ticker: 'AIZ', name: 'Assurant, Inc.' },
    { ticker: 'CRL', name: 'Charles River Laboratories International, Inc.' },
    { ticker: 'HAS', name: 'Hasbro, Inc.' },
    { ticker: 'MTCH', name: 'Match Group, Inc.' },
    { ticker: 'GL', name: 'Globe Life Inc.' },
    { ticker: 'PNW', name: 'Pinnacle West Capital Corporation' },
    { ticker: 'QRVO', name: 'Qorvo, Inc.' },
    { ticker: 'CZR', name: 'Caesars Entertainment, Inc.' },
    { ticker: 'FRT', name: 'Federal Realty Investment Trust' },
    { ticker: 'PAYC', name: 'Paycom Software, Inc.' },
    { ticker: 'APA', name: 'APA Corporation' },
    { ticker: 'HSIC', name: 'Henry Schein, Inc.' },
    { ticker: 'WBA', name: 'Walgreens Boots Alliance, Inc.' },
    { ticker: 'MOS', name: 'The Mosaic Company' },
    { ticker: 'BWA', name: 'BorgWarner Inc.' },
    { ticker: 'IVZ', name: 'Invesco Ltd.' },
    { ticker: 'FMC', name: 'FMC Corporation' },
    { ticker: 'PARA', name: 'Paramount Global' },
    { ticker: 'BBWI', name: 'Bath & Body Works, Inc.' }
];

export default stocks;
